# Generated by Django 4.0.5 on 2022-06-25 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='birth',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
