# Generated by Django 4.0.5 on 2022-06-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes_app', '0002_alter_students_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='students',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='students',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='students',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
    ]
