# Generated by Django 4.0.5 on 2022-07-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes_app', '0003_remove_students_birth_remove_students_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.CharField(max_length=255)),
                ('camada', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
