# Generated by Django 4.0.5 on 2022-07-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes_app', '0004_cursos_delete_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.IntegerField()),
                ('curso', models.CharField(max_length=255)),
            ],
        ),
    ]
